package.json
yarn.lock

There are tons of warnings during dependencies installation.
```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["@storybook/addons@next"] is trying to unpack in the same destination "/Users/jsomsanith/Library/Caches/Yarn/v6/npm-@storybook-addons-6.0.0-alpha.25-f8cc2496b20cfdf4cd213be091ff040aee5c04d3-integrity/node_modules/@storybook/addons" as pattern ["@storybook/addons@6.0.0-alpha.25","@storybook/addons@6.0.0-alpha.25","@storybook/addo …
```

chore: remove some dependency warnings

---

yarn.lock

Storybook doesn't work anymore
The error is still not clear. But I removed yarn.lock and regenerated it and it works again.

fix: resolve dependencies

---

.github/workflows/end-to-end.yml
cypress.json
cypress/integration/components/Button.spec.js
cypress/integration/components/Link.spec.js
cypress/integration/components/Tag.spec.js
cypress/integration/components/Toggle.spec.js
package.json
yarn.lock

chore: Cypress support

---

package.json
src/components/Icon/Icon.tsx

name is missing and we need it for backward compat
add name back

fix(Icon): add name attribute

---

.storybook/main.js
package.json
yarn.lock

It's hard to document all User interactions related states, out of the box.
Add an addon for that.

doc(storybook): addon pseudo states

---

.storybook/manager-head.html
.storybook/preview-head.html

Use preconnect for performance issues

chore(fonts): use preconnect

---

src/components/Button/docs/Button.stories.mdx

Hooks don't work inside story anymore
Quick fix

fix(e2e): buttons

---

.github/workflows/build-and-deploy.yml
.github/workflows/chromatic.yml
.github/workflows/end-to-end.yml
.github/workflows/publish.yml
.github/workflows/umd-size-checker.yml

There is no UMD size checker over the time
Now there is.

chore(GitHub): Actions

---

.storybook/main.js
.storybook/preview.js
package.json
src/components/IconsProvider/IconsProvider.tsx
yarn.lock

Chromatic was stuck since we use Promise.any
Add polyfills

chore: chromatic support

---

src/Welcome.js

The illustration was too generic
Add Talend-ish illustration on the Homepage

doc(Welcome): illustration

---

src/components/Form/Field/Field.style.ts
src/components/Switch/Switch.tsx
src/styled.d.ts
src/tokens/colors.tokens.ts

There are some lint errors
Fix them using TS 

fix(TypeScript): lint errors

---

.storybook/manager-head.html
.storybook/preview-head.html
src/Welcome.stories.mdx
src/docs/Grid.component.js

The font styles on the Welcome page was not consistent with the sections
The title and the text paragraph has been updates

doc(Welcome): update the font styles

---

.storybook/preview-head.html

ToC hasn't the right font family
Fix CSS selectors 

doc(Welcome): ToC font-family

---

src/GettingStarted.stories.mdx

The Figma link used in the Getting Started page was not the good
The link has been updated and redirect now on the Figma Library

doc(Getting Started): Figma link

---

src/components/Button/Button.tsx
src/components/Link/Link.tsx

fix(tsc): issues

---

src/components/Link/Link.tsx
src/components/ThemeProvider/index.js

Unit tests don't pass anymore because typo
Fix typo and css import

fix(tests): typo

---

package.json

**What is new?**
- #79 
- #71 

chore(release): 1.0.8

---

src/docs/Grid.component.js

CSS Grid is messed up on the homepage
Change `minmax` value to `0`  since it will be set to `1fr` for small screens 

doc(Home): css grid

---

src/components/Button/docs/Button.stories.mdx
src/components/Dropdown/docs/Dropdown.stories.mdx
src/components/HeaderBar/docs/HeaderBar.stories.mdx
src/components/InlineMessage/docs/InlineMessage.stories.mdx
src/components/Link/docs/Link.stories.mdx
src/components/Modal/docs/Modal.stories.mdx
src/components/Switch/docs/Switch.stories.mdx
src/components/Tag/docs/Tag.stories.mdx
src/components/Toggle/docs/Toggle.stories.mdx

Figma links are not up to date, and zoning are the previous ones
Fix the links

doc(components): zoning links

---

.storybook/main.js
package.json
yarn.lock

Multi devices are hard to manage while developing
Using Browser-Sync, it's pretty easy to see what you get on desktop and tablet at the same time

chore(Storybook): Browser-Sync support

---

package.json
yarn.lock

Security issues cannot be automatically fixed by dependabot
Use Yarn resolutions

chore(Security): upgrade dependencies

---

.storybook/preview.js
src/components/Button/docs/Button.stories.mdx
src/components/Form/docs/Input.checkbox.stories.mdx
src/components/Form/docs/Input.password.stories.mdx
src/components/Form/docs/Input.radio.stories.mdx
src/components/Form/docs/Input.range.stories.mdx
src/components/Form/docs/Input.search.stories.mdx
src/components/Form/docs/Input.select.stories.mdx
src/components/Form/docs/Input.stories.mdx
src/components/Form/docs/Input.switch.stories.mdx
src/components/Form/docs/Input.textarea.stories.mdx
src/components/Tabs/docs/Tabs.stories.mdx
src/components/Tag/docs/Tag.stories.mdx
src/components/Toggle/docs/Toggle.stories.mdx
src/components/Tooltip/docs/Tooltip.stories.mdx
src/docs/FigmaIframe.component.js
src/docs/index.js

There is no way to embed Figma content into the page.
Hit <kbd>i</kbd> key now to display the Figma stuff and <kbd>m</kbd> to switch between light and dark modes

doc(Storybook): Figma embed

---

src/components/Button/docs/Button.stories.mdx

The Button page needs to read again
Fix typo and headings

doc(components/Button): guidelines

---

.github/PULL_REQUEST_TEMPLATE.md

Changelog was missing from PR checklist
Add it to the checklist

chore(PR_TEMPLATE): add changelog in PR checklist

---

.changeset/stale-rice-happen.md
src/components/IconsProvider/IconsProvider.test.tsx
src/components/IconsProvider/IconsProvider.tsx
src/components/IconsProvider/__snapshots__/IconsProvider.test.tsx.snap
src/docs/Icons.component.js
yarn.lock

- We don't have tests yet for the IconsProvider component.
- The condition to prevent multiple rendering of the component is not yet working
- Add a test
- Fix the condition

fix(IconsProvider): prevent multiple rendering

---

.github/workflows/test.yml

chore(ci): Upload cypress videos

---

.github/workflows/chromatic.yml
.storybook/main.js
.storybook/preview.js
package.json
yarn.lock

Due to GH permissions change, Chromatic was disabled
Now it's working again! 🎉 
https://www.chromatic.com/builds?appId=60b780842fdd2c0039f634e9&branch=frassinier%2Fchore%2Fchromatic_support

fix(Chromatic): Canvas were disabled

---

src/tokens/colors.tokens.ts
src/tokens/docs/Tokens.stories.mdx

Gradients were not documented
Add them into a specific category "gradients" in the tokens page

doc(Tokens): Gradients

---

.changeset/sour-buses-agree.md
package.json
src/components/InlineMessage/InlineMessage.style.ts
src/components/InlineMessage/docs/InlineMessage.stories.mdx
src/components/InlineMessage/index.ts
src/components/InlineMessage/variations/InlineMessage.destructive.tsx
src/components/InlineMessage/variations/InlineMessage.information.tsx
src/components/InlineMessage/variations/InlineMessage.success.tsx
src/components/InlineMessage/variations/InlineMessage.warning.tsx
yarn.lock

InlineMessage depends on the ThemeProvider presence
Use CSS variables to  get rid of this constraint

feat(InlineMessage): CSS variables support

---

.storybook/preview.js

Reverts Talend/design-system#167

Revert "chore(Storybook): prettier"

---

.storybook/preview.js

#167 was a fail about code formatter support
Fix that

chore(Storybook): prettier

---

.storybook/main.js
src/components/Link/Link.stories.tsx
src/components/Link/docs/Link.stories.mdx

New Component Story Format has raised up
Implement it for links

chore(Storybook): CSF 3.0

---

src/components/Card/Card.style.ts
src/components/Combobox/Combobox.style.ts
src/components/HeaderBar/HeaderBar.style.ts
src/components/Layout/SkipLinks/SkipLinks.style.ts
src/components/Menu/Menu.style.ts
src/components/Skeleton/Skeleton.style.ts
src/components/ThemeProvider/ThemeProvider.style.ts
src/pages/blocks/SignupCTA.tsx

No IDE syntax highlighting for anonymous function while using styled-components
Back to simple template string

chore(components): styled syntax

---

.changeset/breezy-shirts-happen.md
src/templates/Step.tsx
src/templates/docs/Templates.stories.js
src/templates/index.js

Step by step UX pattern needs a template
Let's add it

feat(templates): Step

---

src/content/docs/VoiceAndTone.stories.mdx

fix(docs): succinct instead of succint

---

.changeset/little-parents-grin.md
.storybook/main.js
.storybook/preview.js
src/components/Drawer/Drawer.component.tsx
src/components/Drawer/Drawer.stories.tsx
src/components/Drawer/Drawer.style.ts
src/components/Drawer/docs/Drawer.stories.mdx
src/components/Drawer/index.ts
src/components/Layout/Layout.style.ts
src/components/Layout/Layout.tsx
src/components/Layout/docs/Layout.stories.js
src/components/Modal/Modal.style.ts
src/components/Popover/Popover.style.ts
src/docs/Area.component.js
src/docs/index.js
src/index.js
src/pages/ docs/Pages.stories.js
src/pages/Home.tsx
src/templates/docs/Templates.stories.js
src/tokens/shadows.tokens.js
src/tokens/zIndices.tokens.js

No guidelines for Drawer
Add it

feat(components): Drawer

---

.changeset/silver-weeks-chew.md
src/components/Accordion/Accordion.style.ts
src/components/Accordion/docs/Accordion.stories.mdx

doc(Accordion): Clarification and application of the doc

---

.changeset/clever-mice-kick.md
src/components/Combobox/Combobox.tsx
src/components/Combobox/docs/Combobox.stories.mdx

feat(Combobox): Fixing types

---

.github/workflows/percy.yml
.percy.yml
package.json
yarn.lock

We don't have any solution for continuous visual non-regression testing
Try Percy

chore(Tests): Percy support

---

.changeset/tasty-plums-pay.md
src/components/Link/Link.spec.tsx
src/components/Link/Link.tsx

fix(Link): Link target attribute should be preserved on subcomponent

---

yarn.lock

Reverts Talend/design-system#232

Revert "chore(deps-dev): bump prettier from 2.2.1 to 2.4.0"

---

package.json
src/components/Icon/__snapshots__/Icon.test.js.snap
yarn.lock

chore(dependencies): upgrade

---

.changeset/sour-coats-beg.md
src/components/Link/Link.stories.tsx
src/components/Link/Link.tsx
src/components/Link/docs/Link.stories.mdx
src/components/Menu/Menu.style.ts

feat(Link): Fixing Link types

---

package.json
yarn.lock

chore(dependencies): resolutions

---

src/components/Form/docs/FormFieldset.stories.mdx

The section about inline message needs an image to illustrate the section
The image example has been added

feat(forms): Inline message example

---

.storybook/main.js
src/DesignSystem.stories.mdx

doc(global): Added design system definition

---

package.json
yarn.lock

Reverts Talend/design-system#282

Revert "chore(deps-dev): bump @types/react from 16.14.15 to 17.0.26"

---

.changeset/slow-boats-count.md
src/Catalog.stories.mdx
src/components/Button/variations/Button.icon.tsx
src/components/Toggle/Toggle.style.ts

there is a border on the Icon Button, and it should not
remove it, and add a border to the Toggle component

fix(components/button): move icon button border to toggle

---

.changeset/eight-dragons-provide.md
src/components/Stepper/Progress/variations/Progress.vertical.ts
src/components/Stepper/Step/Step.style.ts
src/components/Stepper/Step/variations/Step.disabled.tsx
src/components/Stepper/Step/variations/Step.enabled.tsx
src/components/Stepper/Step/variations/Step.error.tsx
src/components/Stepper/Step/variations/Step.progress.tsx
src/components/Stepper/Step/variations/Step.validated.tsx
src/components/Stepper/docs/Stepper.step.stories.mdx
src/components/Stepper/docs/Stepper.stories.mdx

Steps design has changed and some states are no longer neeeded
Remove ErrorStep
Remove DisabledStep
Update other steps design

feat(components): Stepper style and updates

---

.changeset/perfect-ghosts-rest.md
src/components/Form/Fieldset/Fieldset.tsx
src/components/Form/Row/Row.tsx

Next part of #339  
Fix missing cases

fix(components/form): Avoid lost state/incoherent state on rerender

---

.changeset/brave-ways-play.md
src/components/Form/FieldGroup/FieldGroup.tsx
src/components/Form/docs/Input.group.stories.mdx
src/components/Form/docs/Input.switch.stories.mdx

fix(Form): preserve ref inside fieldgroup

---

.changeset/rotten-bikes-mix.md
src/index.js
src/themes/themes.scss

fix(themes): export
