- src/components/Icon/Icon.tsx
The UI Icon component put attribute name on svg element.
Some test rely on it.
But it is not valid :/
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
add a className to replace it.
> fix(Icons): replace name attribute by class tc-icon-name-

- package.json
- src/components/Button/Button.tsx
- src/components/Form/Field/Input/Input.File.js
- src/components/Form/Field/Select/Select.js
- src/components/HeaderBar/docs/HeaderBar.js
- src/components/Icon/Icon.tsx
- src/components/Link/Link.tsx
- src/docs/Icons.component.js
- src/pages/blocks/HeaderBar.tsx
**Icon** should use currentColor by default
**Icon** has now `preserveColor` instead of `currentColor` props
> feat(Icon): preserveColor props

- package.json
- src/components/Icon/Icon.tsx
Icons used setting a currentColor by default in Talend/ui
Let's keep this behavior for now
> fix(Icons): currentColor

- src/components/IconsProvider/IconsProvider.tsx
The IconsProvider component allow to define several icon bundles to fetch.
When an icon try to render, it use the provider to search the right icon in all bundles. To do that, it waits all bundles to have been fetched. If one of the bundle take an anormal amount of time to load, it delays all icons display.
For example, if you go to pipeline designer, processors icons can take 3s to load (depends on the number of engine and processor you can access to). So the page loads without any icons for almost 4s.
Instead of waiting all bundles to be loaded, try to display the icon everytime a new bundle is loaded.
To do that, the Promise.all made on bundles is replaced by Promise.any.
**Please check …
> chore(components): IconsProvider wait for all bundles

- src/components/IconsProvider/IconsProvider.tsx
We used to create an SVG provider without a namespace, which it's not a real SVGSVGElement
Add the namespace
> fix(iconsprovider): create svg using namespace

- src/components/Switch/Switch.style.ts
- src/components/Switch/Switch.tsx
- src/components/Switch/docs/Switch.stories.mdx
`Switch` has no onChange handler
Add it to each radio button
```jsx
<Switch onChange={(event, value) => console.log(value)} values={['a', 'b', 'c']} />
```
> feat(Switch): onChange

- src/components/Accordion/Accordion.style.ts
- src/styled.d.ts
- src/themes/dark.theme.ts
- src/themes/light.theme.ts
`Accordion` was too shinny with dark mode
Add some design tokens to temp fix this
> feat(Accordion): dark mode

- src/components/Tabs/Tabs.style.ts
`Icon` color was fixed to the default text color.
It's wrong when the tab is active.
Use `currentColor` as default
> fix(Tabs): icon color when active

- package.json
- yarn.lock
TOC used to be shown even if there is no headings
Fix its display and add max-width on its links
> doc: bump TOC version

- src/components/Tag/Tag.style.ts
- src/tokens/fonts.tokens.js
- src/tokens/lineHeights.tokens.js
Tag `line-height` was inherited
Fix it to `1`
> fix(Tag): line-height

- .github/workflows/chromatic.yml
GH Action used to run immediately for all PR 
At least, for Chromatic, wait until the label is set on
> chore(Chromatic): run GitHub action only on label

- src/components/IconsProvider/IconsProvider.tsx
- src/components/ThemeProvider/index.js
- src/docs/Icons.component.js
We can't use `display: none` on `<svg>` sprite for defining filters especially on Firefox
It will solve https://github.com/Talend/ui/pull/3246
> fix(icons): filter

- .babelrc
Next.js used to modify .babelrc and it fails while building UMD
Revert
> chore(babel): revert to previous config

- .babelrc
- src/docs/Grid.component.js
Grid doc component has to a huge gap
reduce it
> doc(grid): reduce gap

- src/components/Button/variations/Button.icon.tsx
Icon Button has a too big icon
Reduce its size according to what was designed in Figma
> feat(button.icon): reduce icon size

- package.json
Types are not exposed automatically
Add the types index in the package.json
> chore(Typescript): expose types in package.json

- .storybook/main.js
- .storybook/preview-head.html
- package.json
- src/components/Link/docs/Link.stories.mdx
Design tokens values were hardcoded
Let's use Design tokens names instead to be able to retrieve their values.
---
---
> doc(Storybook): Design Tokens resolution

- src/components/ThemeProvider/index.js
Open Sans was never in used
Let's replace by the correct one: Source Sans Pro
> fix(ThemeProvider): Source Sans Pro instead of Open Sans

- .storybook/main.js
- package.json
The default behavior while navigating trough Storybook is set on `Canvas` tab, which it's not really convenient!
Pass `--docs` while building Storybook
> doc(Storybook): Docs tab by default

- .changeset/eleven-walls-crash.md
- package.json
`postinstall` script was not in the package.json and changeset doesn't release components
Add `postinstall` script
> chore(changeset): postinstall script

- .changeset/fast-birds-learn.md
- .npmignore
- package.json
https://unpkg.com/browse/@talend/design-system@1.1.2/
contains and should not:
* .changeset folder
* pages
* cypress
At Talend we use apache-2.0 licence
visibility of the package is private.
* switch to access public (all previous release also using npm cli)
* add unwanted content into npmignore
* update license
> chore: cleanup release

- .changeset/dull-parents-report.md
- src/components/Stepper/Step/Step.style.ts
- src/components/Stepper/Stepper.style.ts
- src/components/Stepper/docs/Stepper.overview.stories.mdx
The Stepper related progress bar was discontinued when there is an error
Fix that line to not be discontinued.
> fix(components): Stepper

- .github/workflows/publish.yml
- package.json
current changeset fails to publish because of webpack stdout managements.
remove prepublishOnly
add build scripts call in CI
> fix(CI/release): remove prepublishOnly which makes changeset fails

- src/docs/FigmaImage.js
- static/sw.js
If you don't use a Figma token via the env var `STORYBOOK_FIGMA_ACCESS_TOKEN`, it can fail with a fullscreen error.
Add errors management to not be annoying.
> chore(Storybook): FigmaImage error management

- src/components/InlineMessage/InlineMessage.style.ts
- src/components/InlineMessage/InlineMessage.tsx
- src/components/InlineMessage/docs/InlineMessage.stories.mdx
- src/components/InlineMessage/variations/InlineMessage.destructive.tsx
`InlineMessage.Destructive` uses the wrong icon and `Inline Message` style can be simplified
Change  the  icon and simplify its style
> fix(components): Inline Message

- .changeset/new-icons-listen.md
- src/components/Link/Link.spec.tsx
- src/components/Link/Link.style.ts
- src/components/Link/Link.tsx
- src/components/Link/docs/Link.stories.mdx
Link can have double underline
Get rid of the text decoration
> fix(Link): underline

- .changeset/rude-gifts-tease.md
- src/Catalog.stories.mdx
- src/components/Button/variations/Button.base.tsx
- src/components/InlineMessage/InlineMessage.style.ts
- src/components/Link/Link.style.ts
Can't use `Link` as "button" or `Button` as "a"
Adapt style to match new element
> feat(CTA): keep style when using as

- .changeset/hungry-needles-drum.md
- src/components/Stepper/Progress/variations/Progress.horizontal.ts
- src/components/Stepper/Progress/variations/Progress.vertical.ts
Progress bar style is messed up using Bootstrap stylesheet
Increase style weight
> fix(components): stepper progress bar style

- .storybook/preview.js
Source preview can be a mess
Use Prettier to clean it up
Linked to https://github.com/storybookjs/storybook/issues/8078
> chore(Storybook): prettier

- .changeset/calm-chairs-wash.md
- src/components/InlineMessage/InlineMessage.style.ts
- src/components/InlineMessage/InlineMessage.tsx
- src/components/InlineMessage/docs/InlineMessage.stories.mdx
InlineMessage default CSS properties were  hardcoded 
Inherit instead
> fix(InlineMessage): default colors should inherit

- .changeset/silent-windows-dress.md
- src/components/Form/Field/Field.style.ts
Focus outline was visible every time
Show it only when using the keyboard
> fix(Forms): focus outline should not be visible using mouse

- src/components/Stepper/Progress/Progress.style.ts
- src/components/Stepper/Progress/variations/Progress.horizontal.ts
- src/components/Stepper/Progress/variations/Progress.vertical.ts
The progress bar for the stepper has really common class name which can be used in the project
Scope it
> fix(Stepper): Progress bar classnames need to be more precise

- .changeset/little-rocks-jam.md
- src/templates/Step.tsx
Step template was not working with dark mode
Use theme instead to be able to switch 
> fix(templates): Step with dark mode

- .changeset/clever-flowers-argue.md
- src/components/Layout/Layout.style.ts
- src/components/Layout/Layout.tsx
- src/components/Menu/Menu.style.ts
- src/templates/List.tsx
- src/templates/docs/Templates.stories.js
Nav width in templates was not managed correctly
Adjust the nav width when templates display a menu
> fix(Templates): nav width

- .github/workflows/test.yml
- cypress/support/index.js
- package.json
- src/components/Button/Button.spec.tsx
- src/components/Button/Button.stories.tsx
- src/components/Button/docs/Button.stories.mdx
- src/components/Link/Link.spec.tsx
- src/components/Link/Link.stories.tsx
- src/components/Tag/Tag.spec.tsx
- src/components/Tag/Tag.stories.tsx
- yarn.lock
Stories and E2E tests don't use the same JSX element
Define JSX once in the story and run E2E tests using the story too
> chore(Tests): @storybook/testing-react

- package.json
- src/components/IconsProvider/IconsProvider.tsx
- yarn.lock
Typescript is not in dev dependencies
Add it and fix tsc issue 
> chore(Typescript): add as dev dependency

- .changeset/happy-bottles-build.md
- src/components/InlineMessage/InlineMessage.stories.tsx
- src/components/InlineMessage/InlineMessage.style.ts
- src/components/InlineMessage/InlineMessage.tsx
- src/components/InlineMessage/docs/InlineMessage.stories.mdx
- src/components/InlineMessage/variations/InlineMessage.destructive.tsx
- src/components/InlineMessage/variations/InlineMessage.information.tsx
- src/components/InlineMessage/variations/InlineMessage.success.tsx
- src/components/InlineMessage/variations/InlineMessage.warning.tsx
InlineMessage has no readable className for its variations
Add it and harmonize its custom properties naming
> fix(components/InlineMessage): className was missing for variations

- .changeset/kind-rats-taste.md
- src/components/InlineMessage/InlineMessage.style.ts
If the container has text-align at the center, then the text of InlineMessage will be centered
Force the text of InlineMessage to be at start
> fix(components/InlineMessage): text-align at start

- .changeset/violet-carrots-compare.md
- src/components/Accordion/Accordion.tsx
- src/components/Form/Buttons/Buttons.tsx
- src/components/Form/Fieldset/Fieldset.spec.tsx
- src/components/Form/Fieldset/Fieldset.tsx
- src/components/Form/Form.tsx
Usage of index as key will break component state if children change.
https://reactjs.org/docs/lists-and-keys.html
`We don’t recommend using indexes for keys if the order of items may change. This can negatively impact performance and may cause issues with component state. `
Don't use keys when you can't assume the elements will not change/reorder
> fix(components): Usage of index as key breaks component state

- .changeset/dry-tomatoes-grow.md
- src/components/ThemeProvider/ThemeProvider.tsx
We have nested ThemeProvider in TUI Layout, which is not ideal but something we have to deal with
```
<ThemeProvider theme={theme}>
<ThemeProvider>
<Component/>   
</ThemeProvider>
</ThemeProvider>
```
> fix(ThemeProvider): Handle nested providers

- .changeset/moody-suits-pump.md
- src/components/ThemeProvider/ThemeProvider.tsx
- src/themes/index.ts
Theme dictionary  was not in the UMD
Add them all
> feat(themes): Expose dictionaries into the UMD

- .changeset/neat-waves-whisper.md
- src/components/Form/Field/Input/Input.Copy.tsx
- src/components/Form/docs/Input.copy.stories.mdx
Copy field had a controlled value
Let's spread props to be able to use RHF
> fix(form): Copy field uncontrolled value

- .changeset/poor-seals-behave.md
- src/components/Switch/Switch.style.ts
- src/components/Switch/Switch.tsx
- src/components/Switch/docs/Switch.stories.mdx
At the very first render, switch indicator has an animation
Remove the animation only for first render
> fix(components/switch): no animation with defaultValue
